#
# Please edit this configuration file to match your environment (on Windows).
# Examples in comments below - check/change the paths.
#
#
default_model: openai.gpt-4.1-nano

otel:
  enabled: true # Enable or disable OpenTelemetry

logger:
  type: console
  level: error
  truncate_tools: true

mcp:
  servers:
    mcp-searxng:
      command: "npx"
      args: ["-y", "mcp-searxng"]
      env:
        SEARXNG_URL: "http://192.168.194.33:8060"
    filesystem:
      # On windows update the command and arguments to use `node` and the absolute path to the server.
      # Use `npm i -g @modelcontextprotocol/server-filesystem` to install the server globally.
      # Use `npm -g root` to find the global node_modules path.`
      # command: "node"
      # args: ["c:/Program Files/nodejs/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js","./agent_folder"]
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "./agent_folder/"]
    interpreter:
      command: "docker"
      args: [
          "run",
          "-i",
          "--rm",
          "--pull=always",
          "-v",
          "./agent_folder:/mnt/data/",
          # Docker needs the absolute path on Windows (e.g. "x:/fastagent/agent_folder:/mnt/data/")
          # "./agent_folder:/mnt/data/",
          "ghcr.io/evalstate/mcp-py-repl:latest",
        ]
      roots:
        - uri: "file://./agent_folder/"
          name: "agent_folder"
          server_uri_alias: "file:///mnt/data/"
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    sequential:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]
#    webmcp:
#      command: "node"
#      args: ["/home/ssmith/.webmcp/server.cjs"]
#      env:
#         WEBMCP_SERVER_TOKEN: 96e22896d8143fc1d61fec09208fc5ed
