services:
  jaeger:
    image: jaegertracing/all-in-one:1.69.0
    container_name: jaeger
    ports:
      - "16686:16686" # Web UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "5778:5778" # Config server
      - "9411:9411" # Zipkin compatible
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://192.168.194.33:9200
      - ES_USE_ALIASES=true
    restart: unless-stopped
